### PR TITLE
Content Forms Improvements

### PR DESCRIPTION
**Pull request by cristian-ungureanu**
**What's new:**

- Better organize the code and files
- Fixed the issues with the required fields ( https://github.com/Codeinwp/themeisle-companion/issues/338 )
- Fixed the issue with the Beaver Modules registering multiple times ( https://github.com/Codeinwp/themeisle-companion/issues/384 )
- Added the possibility to change the success or error messages for contact and newsletter widgets ( https://github.com/Codeinwp/themeisle-content-forms/issues/35 )
- Added the possibility to register with the newsletter widget not only the email and name but also the other fields that MailChimp or SendinBlue allows
- Added the option to hide all form labels
- Added the styling controls for beaver widgets ( almost the same as Elementor forms have )

**How to install it:**

1. Get the development branch of Orbit Fox: https://github.com/Codeinwp/themeisle-companion/tree/development
2. Run composer install in a terminal
3. Replace the themeisle-content-forms folder in vendor/codeinwp/ with this one ( the dev branch of this repo )

**Testing suggestions:**

1. Check that all style options are working ( I've tested them but maybe I missed something )
2. Check the mobile part. ( I haven't had time to test it but I will too )

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I have two things I got stuck at while testing:
- from what I understand when using Beaver Builder, OBFX adds a contact form and a newsletter widgets, but I don't know where to find them. Tried creating a page and this is what I see https://prnt.sc/ptu358
- for the newsletter widget what are Access Key and List ID? Where can I find those in Sendinblue?
Thanks

**Comment by cristian-ungureanu** [comment]
@rodica-andronache 
I only called the forms in Elementor Obfx module, If you had Elementor and Beaver it would work. I fixed it and called it in Beaver module too.

For SIB you can find the access key here: https://account.sendinblue.com/advanced/api ... it should look smth like this https://prnt.sc/pu4be2 ... In my account, there are 2 API keys, one for the plugin that I use with their widget and the other APIv3 that you may use for our widget.
You can create a list here: https://my.sendinblue.com/lists and here's the list id https://prnt.sc/pu4i76

**Comment by rodica-andronache** [comment]
@cristian-ungureanu 

The majority are for both Elementor and Beaver Builder. The ones that are specific to just on page builder, have a mention at the beginning.

**1. Issues**

- [x]  For both the Contact Form and Newsletter widgets, on frontend, on the single post page, the submit button from the `Leave a comment form` becomes full width. Same for the search button in the sidebar. 
https://prnt.sc/ptt24e as a reference, this is a normal post https://prnt.sc/pttc4f.
The screenshots are from Twenty Nineteen but same happens on Neve

- [x]  Chose SendinBlue as a provider for the newsletter widget. Tried to enter an email address in the Email field of the newsletter widget. => RESULT: The email was not registered. An error appeared "attributes should be an object" https://prnt.sc/pvave5

- [x]  Chose MailChimp as a provider for the newsletter widget. Tried to enter an email address in the Email field of the newsletter widget. => RESULT: This error appeared: "The resource submitted could not be validated. For field-specific details, see the 'errors' array."

- [x] _[JUST FOR ELEMENTOR]_ In the Newsletter widget, after running a Sendinblue test, tried to switch to MailChimp and delete the current Provider Settings ( to enter the ones for MailChimp instead of SendinBlue ). 
The fields for Access Key and List id can't be deleted. https://www.loom.com/share/a27ea952a1354ec2b2e9c8f3d847ef56

- [x] _[JUST FOR BEAVER BUILDER]_ Contact Form widget - Alignment option not working for the Submit button https://prnt.sc/pu80v2

**2. Suggestions**

- [x] _[JUST FOR ELEMENTOR]_ In the Newsletter widget, adding an icon, makes the icon stick to the text,  without any spacing https://prnt.sc/pttweq. Changing the Icon spacing control should help with this,
but the option adds spacing both left and right for the icon, making the text and icon not look centered in the button https://prnt.sc/pttxln. Not sure how it would be best to approach this, but I think is not very useful right now

- [x] Both in Contact and Newsletter widgets, move the _Hide Label_ option in the _Fields_ tab (as it's related to the form fields), and rename it to _"Use Labels as Placeholders"_

- [x] In the Contact form, if the success message option is left empty, a tiny box appears after the form is submitted. I would suggest that if no message is entered, we use the default text. https://prnt.sc/pttopo

- [x] in the Style tab, all subtabs have the same order of options: Color + Typography. 
Just the Field subtab has the order Typography + Colors. I think that could be changed to match the other options. ( same for Newsletter widget and Contact form widget )

- [ ] Mention somewhere in the plugin, where you can get the Access key and List id for both SendinBlue and MailChimp, as each provider has different names for them, and it can be difficult to understand.

**3. Questions**

- [x] For the Contact form, not sure how to test the Fail message option as no matter the settings, email address, the message is successful, but the email is not sending.

- [x] How to check in Mailchimp that the email was registered?

**4. Related to Neve**

- [x]  _[JUST FOR BEAVER BUILDER]_ https://prnt.sc/pu7ok9 - In the Contact Form widget, when the Hide Label option is checked, all the forms inputs get stuck together

- [ ] _[JUST FOR BEAVER BUILDER]_ https://prnt.sc/pu7mwp - In the Contact Form widget, the submit form gets stuck to the form

Here is everything I tested, if there are things I'm missing let me know, or if this way of reporting the issue could be improved 👍 

https://docs.google.com/spreadsheets/d/1olx56SW-ThY8hmwKS2epZS-r6IVAy3OcoxlijeEEqv8/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1xlVcy_qF58lO75Q5bJZKEIKCeeL_Ye3pqpFGM62iHLw/edit?usp=sharing

**Comment by cristian-ungureanu** [comment]
@rodica-andronache 
- I don't know exactly where to add the description about the API key and list id. Can you suggest something?

- The contact form can be tested on jurassic.ninja, I didn't manage to make it work on local. Depending on your email, it may arrive in the spam folder. For example, on my personal address arrived in the inbox while on @themeisle address it arrived in spam. The fail message will either appear if the email address is invalid ( in that case the message is "Wrong email configuration! Please contact administration!" ) or if the wp_mail function returns "false" ( the message is the one configured by the user )

- I moved thee hide label but I won't change the label with "Use Labels as Placeholders". You can add both labels and placeholders. It may be confusing as from "Use Labels as Placeholders" I understand that if I add something in the label field it will be displayed as a placeholder (and this does not happens )

- I've fixed the error with the subscribe widget and now it should work. If you are using MailChimp you should receive an email asking if you want to subscribe.
Also, there are multiple fields that can be added to the subscribe form, just make sure you add  the following values in "Map field to" (in repeater):

MailChimp:
Email => Map field to: email ( If this is missing => submit form error )
First Name => Map field to: fname
Last Name => Map field to: lname
Address => Map field to: address
( Note: MailChimp has this dumb approach and if you need an address field, it automatically split the address in "Addreess line 1", "Address line 2", "City", "Country", "Postal Code" etc. so I added those fields automatically when you write address in Map field to )
Birthday => Map field to: birthday

SendInBlue:
Email => Map field to: email ( If this is missing => submit form error )
Name => Map field to: name
Surname => Map field to: surname

MailerLite:
Email => Map field to: email ( If this is missing => submit form error )
Name => Map field to: name
Last Name => Map field to: last_name
Company => Map field to: company
Country => Map field to: country
City => Map field to: city
Phone  => Map field to: phone
State => Map field to: state
Zip => Map field to: zip

I think all of this services allow you to add custom fields ( didn't test with that but it should work )

**Comment by rodica-andronache** [comment]
@cristian-ungureanu thanks for the details. I run the tests again and added new ones for extra fields you mentioned. I still need to test the MailerLite part ( I didn't manage to create an account yet ) and the contact form on an on-line instance ( I've tried with Beaver on my site, and it didn't work, but we'll try again on jurassic )

- [ ] For the description about the API key and List id I would suggest we have a doc about it and link the doc in the newsletter Provider Settings panel like "Check here to see where you can get the Access Key and List ID". Maybe there we can mention the part with mapping the fields ( I can help with the doc )

- [x] Ok, for the Hide Label field renaming. It’s just that is still in the Form Settings tab for the Elementor and Beaver Contact Form widget https://prnt.sc/pvx0dd

- [x] In both Elementor and Beaver Builder, for **SendinBlue**, in the Newsletter widget, which has the Email field, I've done:
Add a new field in the newsletter widget, with the label "Name" and Map field to "name".
Add a new field in the newsletter widget, with the label "Surname" and Map field to "surname".
Make all fields required.
=> The email is registered, but not the name and surname. https://prnt.sc/pvyjoo

- [x] In both Elementor and Beaver Builder, for **MailChimp**, in the Newsletter widget, which has the Email field, I've done:
Add a new field in the newsletter widget, with the label "First Name" and Map field to "fname".
Add a new field in the newsletter widget, with the label "Last Name" and Map field to "lname".
Add a new field in the newsletter widget, with the label "Birthday" and Map field to "birthday".
Add a new field in the newsletter widget, with the label "Phone" and Map field to "phone".
Add a new field in the newsletter widget, with the label "Address" and Map field to "address".
Make all fields required.
=> When the birthday field is there, this error message appears "Your merge fields were invalid." https://prnt.sc/pvybof. The email is not registered.
If the birthday field is not used, the email is registered correctly.

For the birthday field, I've used this format, as this is what I've seen mentioned on Mailchimp YYYY-MM-DD

As a suggestion: if possible rename Line 2 to Address Line 2, and all width components in the form of 'Country Field Width' for e.g instead of 'Country Width'

As a question, for Beaver Builder, not sure here, if it's supposed to work as for Elementor. The extra fields for the address don't appear in the widget dashboard, so you can't edit the 
placeholders and width of the fields, as in Elementor.

- [x] for Elementor, saw this also:
https://prnt.sc/pvxub3 In the backend, when changing the width of the Country field to less than 50%, the arrow is not positioned well, and on the frontend, the field always stays at 50% https://prnt.sc/pvxvor

- [x] Post type grid pagination tested with Neve https://prnt.sc/pvzrrc

**Comment by cristian-ungureanu** [comment]
@rodica-andronache 
-> For this part https://prnt.sc/pvx0dd, you have two columns, LASTNAME, and FIRSTNAME, that's what you should enter in the "Map field to" field. In my account, this is how it looks like https://prnt.sc/pw968n so I thought that's what it looks like by default ( also, I would suggest not to share a screenshot with lightshot with any mail addresses )

-> Regarding the invalid birthday field, from what I've seen in my account it's this format: MM/DD. You can make a jurassic.ninja instance, install a plugin that allows you to add code in the head area and then connect a site in mailchimp. After that, you'll be able to create a contact form directly in mailchimp and you can see all the fields you can add, there ( https://prnt.sc/pw9x0l )

-> Beaver Builder does not have a mechanism to show/hide fields in the repeater based on another field value so I decided not to add them to avoid any confusion. Those strings are translatable so technically you can change them with mo/po files. The only thing you can't change is the width of the fields. It's not the best approach in elementor either because if you choose sendinblue and map the field to "address", those fields will appear in the repeater but they will not do anything. It's just how those controls work.

**Comment by cristian-ungureanu** [comment]
Personally I would not rename those fields. The labels will become really long and in Elementor Repeater the label is next to the field. It would look like this https://prnt.sc/pwagcj.

**Comment by cristian-ungureanu** [comment]
About those two issues:
[JUST FOR BEAVER BUILDER] https://prnt.sc/pu7ok9 - In the Contact Form widget, when the Hide Label option is checked, all the forms inputs get stuck together

 [JUST FOR BEAVER BUILDER] https://prnt.sc/pu7mwp - In the Contact Form widget, the submit form gets stuck to the form

I cannot change the default style as it will modify the starter sites. There are controls in the style tab to modify the spacing between rows.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu thanks, I've tested everything and here are the remaining things from my side.
- https://www.loom.com/share/e174f2cc8b454e5a84eae80252340d03 in Beaver Builder I can’t add a Contact Form and a Newsletter widget on the same page. It loads forever and if you try to get out, the page gets a fatal error. I've tested on multiple WP Instances and the same thing happened.

- Beaver Builder Contact Form widget - Alignment option not working for the Submit button https://prnt.sc/pu80v2

- Tested again the contact Form on both builders -> indeed not working on local and does work for an online site. Though if you try with an invalid email address, after submit is still shows the success message as if the email is sent.

**Comment by cristian-ungureanu** [comment]
@rodica-andronache about this issue: Beaver Builder Contact Form widget - Alignment option not working for the Submit button. In Beaver Builder, the submit button was made to be inline. First, you need to make the button display block, then align the button. Here's a video about it: https://www.loom.com/share/914099c361674ce4881c1852c7de7955

There's a second control in Style -> Submit button -> Typography -> Align that comes from the typography Beaver control, I cannot remove just one part of it. Because of this, I've added width and height for that button: https://www.loom.com/share/8467b8b6512543018236eaaebc92f62e

The other two issues are fixed now

**Comment by rodica-andronache** [comment]
@cristian-ungureanu thanks for explaining 👍 
The remaining issue for me is the one with the Contact form. 
What I'm trying is to use an invalid email address for `Send to` like `rodi@hmaile.com` for example and submit the form. The success message appears even though the email can't be actually sent to that email address.

**Comment by cristian-ungureanu** [comment]
@rodica-andronache I can't check if an email actually exists. All I can do is to check that the email has a valid form. I am using the is_email function from wp. Here's the documentation: https://developer.wordpress.org/reference/functions/is_email/. The email address is tested to have at least 6 characters, to contain "@" character, it checks for invalid characters, etc. You can have a look at the function's body and see the checks. rodi@hmaile.com  is a valid email, doesn't matter that it doesn't exist.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu ok, I thought there's a possibility to check if the email was actually sent or not ( either because the email address was not valid or did not exist or there was a server error or something ) and show the Fail message. If there isn't anything that can be done, that was everything from my side 👍

**Comment by selul** [comment]
yes, the current check is fine, no need to further do anything.

**Pull request merged**
