### PR TITLE
Undefined message when submitting the Newsletter form

### PR DESCRIPTION
**Pull request by contactashish13**
#23

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@contactashish13 can you please release this, if everything is ok? 👍  We use the form in Neve, and have many users reporting this issue https://github.com/Codeinwp/neve/issues/359. Thanks

**Comment by radu-themeisle** [comment]
I tested the PR using Mailchimp and a Local instance:
1. Newsletter: http://prntscr.com/mic03g; I first entered something wrong on purpose and I got the correct message "Invalid email" (no "[object object" message). But then I put a correct address and I could still see the "invalid email" message plus it added "null" each time I pressed "subscribe now".
2. Contact Form: http://prntscr.com/mic2go; same thing, I first entered wrong details to see the message, then I filled in the form and submitted it. Everything looks good, I get the success message, but it should removed the first error message.

**Comment by contactashish13** [comment]
@radu-themeisle I cannot reproduce this. The old message is correctly removed during my testing. Can you please provide a screen recording? 

I'm trying with the default 2017 theme.

**Comment by radu-themeisle** [comment]
@contactashish13 I tested again, fresh install, theme twentyninteen.
- **Newsletter form**: after imputing a wrong email format and then a good one, the "invalid email" message doesn't disappear and also when imputing the correct email there's a "null" message (I don't think it's related to Mailchimp/Sendinblue not being set up as when I first tested your PR I had Mailchimp set up).
https://www.useloom.com/share/fd1a9b5048d84ceb9e266e01240c868c

- **Contact form**: error messages stack up one on top of the other instead of displaying just the ones that still have errors after I've corrected my wrong input.
I removed the message field but I get an error saying "Missing message".
https://www.useloom.com/share/279b76bc06544e15b4fa81938231c8bb

I put a text area field without making it a required one. If I don't fill it in I get the "Missing message" error, if I fill it in everything is ok and the form works.
https://www.useloom.com/share/42b9e9d0ff6042e098a1ffdcf2860a71

Another thing that I found a bit strange is that if I have several inputs with errors it only tells me "Invalid email". I believe it should list all the field with errors: http://prntscr.com/mr9wdz

- **User Registration form**: I don't really know how this should work, maybe together with Woocommerce or bbpress maybe? I never used this widget and honestly I don't see it's added value, maybe you could see some use cases for it. Otherwise, wouldn't it be best to remove it?
https://www.useloom.com/share/dd4996260d4f4e0284afc25ffda62f5b

**Comment by contactashish13** [comment]
@radu-themeisle in the contact form, you can remove the message field but I don't think contact form will make sense without a message. Nevertheless, I have addressed the issues you uncovered. Same with the newsletter.

I'm not sure either how User Registration was supposed to work. @selul any suggestions?

**Comment by radu-themeisle** [comment]
@contactashish13 everything looks good.
I also pushed a commit with a fix for Firefox because the elements of the fieldset were inline not one on top of the other. Other browsers looked ok.

**Pull request merged**
